# KiriCTF 本地 PostgreSQL 配置。修改后需重启容器才会生效。
listen_addresses = '*'
port = 5432
max_connections = 100
shared_buffers = 128MB
dynamic_shared_memory_type = posix
unix_socket_directories = '/var/run/postgresql'
password_encryption = scram-sha-256
hba_file = '/etc/postgresql/pg_hba.conf'
ident_file = '/etc/postgresql/pg_ident.conf'
datestyle = 'iso, ymd'
timezone = 'Asia/Shanghai'
log_timezone = 'Asia/Shanghai'
log_destination = 'stderr'
logging_collector = off
default_text_search_config = 'pg_catalog.simple'
