// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CheckUpdateData, CheckUpdateErrors, CheckUpdateResponses, DownloadPackageData, DownloadPackageErrors, DownloadPackageResponses, GetChangelogData, GetChangelogErrors, GetChangelogResponses, GetHealthData, GetHealthResponses, GetIntegrityData, GetIntegrityErrors, GetIntegrityResponses, GetOpenApiSpecData, GetOpenApiSpecResponses, GetProjectMediaData, GetProjectMediaErrors, GetProjectMediaResponses, GetPublicProjectData, GetPublicProjectErrors, GetPublicProjectResponses, GetStoreFeedData, GetStoreFeedErrors, GetStoreFeedListingData, GetStoreFeedListingErrors, GetStoreFeedListingResponses, GetStoreFeedResponses, HeadPackageData, HeadPackageErrors, HeadPackageResponses, HeadProjectMediaData, HeadProjectMediaErrors, HeadProjectMediaResponses, ListClientAnnouncementsData, ListClientAnnouncementsErrors, ListClientAnnouncementsResponses, ListClientChannelsData, ListClientChannelsErrors, ListClientChannelsResponses, ListClientLanguagesData, ListClientLanguagesErrors, ListClientLanguagesResponses, ListClientMatrixData, ListClientMatrixErrors, ListClientMatrixResponses, OptionsPublicProjectData, OptionsPublicProjectErrors, OptionsPublicProjectResponses, PostStoreFeedData, PostStoreFeedErrors, PostStoreFeedListingData, PostStoreFeedListingErrors, PostStoreFeedListingResponses, PostStoreFeedResponses, ReportClientData, ReportClientErrors, ReportClientResponses, ReportTelemetryData, ReportTelemetryErrors, ReportTelemetryResponses, UpdateDiffData, UpdateDiffErrors, UpdateDiffResponses, UpdatePackData, UpdatePackErrors, UpdatePackResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 存活与就绪探测
 *
 * 进程还在就返回 200。body.ready 表示数据库能 Ping、对象存储探测键能 Head。未就绪时 ready=false，HTTP 仍是 200。
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/health',
        ...options
    });
};

/**
 * 本平面 OpenAPI 文档
 *
 * 返回这份客户端平面的 OpenAPI 3.0 JSON。
 */
export const getOpenApiSpec = <ThrowOnError extends boolean = false>(options?: Options<GetOpenApiSpecData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetOpenApiSpecResponses, unknown, ThrowOnError>({
        url: '/api/v1/openapi.json',
        ...options
    });
};

/**
 * 读取项目公开设置
 *
 * 不含密钥。用于确认项目存在、是否强制 HTTPS、是否要带客户端 Token。开启 require_client_token 时需要 Bearer 或 X-Project-Token。
 */
export const getPublicProject = <ThrowOnError extends boolean = false>(options: Options<GetPublicProjectData, ThrowOnError>) => {
    return (options.client ?? client).get<GetPublicProjectResponses, GetPublicProjectErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}',
        ...options
    });
};

/**
 * CORS 预检
 *
 * 不要求客户端 Token。Origin 匹配 cors_origins 时回写 Access-Control-Allow-*。
 */
export const optionsPublicProject = <ThrowOnError extends boolean = false>(options: Options<OptionsPublicProjectData, ThrowOnError>) => {
    return (options.client ?? client).options<OptionsPublicProjectResponses, OptionsPublicProjectErrors, ThrowOnError>({
        url: '/api/v1/projects/{project_ref}',
        ...options
    });
};

/**
 * 列出当前可见公告
 *
 * 独立接口，不塞进 check。可用 version/os/arch/locale 做匹配。没有匹配项仍返回 200，announcements 为空数组。草稿和未到展示窗口的不会出现。
 */
export const listClientAnnouncements = <ThrowOnError extends boolean = false>(options: Options<ListClientAnnouncementsData, ThrowOnError>) => {
    return (options.client ?? client).get<ListClientAnnouncementsResponses, ListClientAnnouncementsErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}/announcements',
        ...options
    });
};

/**
 * 列出公开渠道
 *
 * 只返回已启用、未隐藏、不需要渠道口令的渠道。空列表仍是 200。
 */
export const listClientChannels = <ThrowOnError extends boolean = false>(options: Options<ListClientChannelsData, ThrowOnError>) => {
    return (options.client ?? client).get<ListClientChannelsResponses, ListClientChannelsErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}/channels',
        ...options
    });
};

/**
 * 商店协议文档（无文档名）
 *
 * 按协议和 listing slug 输出商店文档，例如 Sparkle appcast。旧的两段路径（把文档名当成 slug）会纯文本 404。listing 钉死的 os/arch/channel 会覆盖冲突的查询参数。
 */
export const getStoreFeedListing = <ThrowOnError extends boolean = false>(options: Options<GetStoreFeedListingData, ThrowOnError>) => {
    return (options.client ?? client).get<GetStoreFeedListingResponses, GetStoreFeedListingErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}/store/{protocol}/{listing_slug}',
        ...options
    });
};

/**
 * 商店协议查询（无文档名）
 *
 * 部分协议用 POST 查清单，例如 WinGet manifestSearch。鉴权和 GET 相同。
 */
export const postStoreFeedListing = <ThrowOnError extends boolean = false>(options: Options<PostStoreFeedListingData, ThrowOnError>) => {
    return (options.client ?? client).post<PostStoreFeedListingResponses, PostStoreFeedListingErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}/store/{protocol}/{listing_slug}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 商店协议文档
 *
 * 路径形如 /store/sparkle/default/appcast.xml。没有 listing slug 的旧路径返回纯文本 404。文档里的 enclosure 指向全量包的 SHA-256 下载地址。未知协议或未启用的 listing 也是纯文本 404。
 */
export const getStoreFeed = <ThrowOnError extends boolean = false>(options: Options<GetStoreFeedData, ThrowOnError>) => {
    return (options.client ?? client).get<GetStoreFeedResponses, GetStoreFeedErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}/store/{protocol}/{listing_slug}/{doc}',
        ...options
    });
};

/**
 * 商店协议查询
 *
 * 例如 WinGet 的 /manifestSearch。请求体由该协议定义，不是本平面的 JSON 信封。
 */
export const postStoreFeed = <ThrowOnError extends boolean = false>(options: Options<PostStoreFeedData, ThrowOnError>) => {
    return (options.client ?? client).post<PostStoreFeedResponses, PostStoreFeedErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}/store/{protocol}/{listing_slug}/{doc}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 列出项目语言
 *
 * 给客户端选语言用。不含 project_id。空列表仍是 200。
 */
export const listClientLanguages = <ThrowOnError extends boolean = false>(options: Options<ListClientLanguagesData, ThrowOnError>) => {
    return (options.client ?? client).get<ListClientLanguagesResponses, ListClientLanguagesErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}/languages',
        ...options
    });
};

/**
 * 列出平台矩阵
 *
 * 每行是 os、arch、package_type。检查更新时 check 也会带回当前目标的 package_type。
 */
export const listClientMatrix = <ThrowOnError extends boolean = false>(options: Options<ListClientMatrixData, ThrowOnError>) => {
    return (options.client ?? client).get<ListClientMatrixResponses, ListClientMatrixErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}/matrix',
        ...options
    });
};

/**
 * 下载 Markdown 配图
 *
 * 按媒体 UUID 取文件。更新日志和公告里的图片走这里，不是安装包下载。
 */
export const getProjectMedia = <ThrowOnError extends boolean = false>(options: Options<GetProjectMediaData, ThrowOnError>) => {
    return (options.client ?? client).get<GetProjectMediaResponses, GetProjectMediaErrors, ThrowOnError>({
        responseType: 'blob',
        url: '/api/v1/projects/{project_ref}/media/{id}',
        ...options
    });
};

/**
 * 探测 Markdown 配图
 *
 * 与 GET 相同的鉴权和校验头，不返回正文。
 */
export const headProjectMedia = <ThrowOnError extends boolean = false>(options: Options<HeadProjectMediaData, ThrowOnError>) => {
    return (options.client ?? client).head<HeadProjectMediaResponses, HeadProjectMediaErrors, ThrowOnError>({
        url: '/api/v1/projects/{project_ref}/media/{id}',
        ...options
    });
};

/**
 * 按 SHA-256 下载全量或增量
 *
 * 按内容 SHA-256 下载全量或增量（kind=full / delta / patch / file 等）。路径里是内容哈希（可带扩展名）。按文件名或产物 UUID 下载已取消。私有项目的 URL 需要 ?exp=&sig=。支持 Range。
 */
export const downloadPackage = <ThrowOnError extends boolean = false>(options: Options<DownloadPackageData, ThrowOnError>) => {
    return (options.client ?? client).get<DownloadPackageResponses, DownloadPackageErrors, ThrowOnError>({
        responseType: 'blob',
        url: '/api/v1/projects/{project_ref}/packages/{ref}',
        ...options
    });
};

/**
 * 按 SHA-256 下载全量或增量
 *
 * 按内容 SHA-256 下载全量或增量（kind=full / delta / patch / file 等）。路径里是内容哈希（可带扩展名）。按文件名或产物 UUID 下载已取消。私有项目的 URL 需要 ?exp=&sig=。支持 Range。
 */
export const headPackage = <ThrowOnError extends boolean = false>(options: Options<HeadPackageData, ThrowOnError>) => {
    return (options.client ?? client).head<HeadPackageResponses, HeadPackageErrors, ThrowOnError>({
        url: '/api/v1/projects/{project_ref}/packages/{ref}',
        ...options
    });
};

/**
 * 上报更新进度
 *
 * 成功一律 202，不要因为上报失败卡住更新。必填 os、arch、channel、from_version、to_version、status。device_id 可选。超限返回 429 RATE_LIMITED。
 */
export const reportTelemetry = <ThrowOnError extends boolean = false>(options: Options<ReportTelemetryData, ThrowOnError>) => {
    return (options.client ?? client).post<ReportTelemetryResponses, ReportTelemetryErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}/telemetry/report',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 检查是否有更新
 *
 * JSON 体必填 current_version、os、arch。200 有可执行更新并带全量包地址；204 已是最新；304 是 ETag 命中。GET 本路径 404。capabilities 与 accepted_delta_algos 为字符串数组。默认下一步：下载 package_url。单文件差量再调 POST /update/diff；多文件比较增量再调 GET integrity 和 POST /update/pack。
 */
export const checkUpdate = <ThrowOnError extends boolean = false>(options: Options<CheckUpdateData, ThrowOnError>) => {
    return (options.client ?? client).post<CheckUpdateResponses, CheckUpdateErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}/update/check',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 查询单文件差量方案
 *
 * 只做查找，不会排队打包。用于 binary_delta、少量文件的 file_list，或预生成的 patch_package。多文件按本地文件比较后打包请用 POST /update/pack。指定目标未进灰度且不是强制更新时 412。降级目标不会给二进制差量。
 */
export const updateDiff = <ThrowOnError extends boolean = false>(options: Options<UpdateDiffData, ThrowOnError>) => {
    return (options.client ?? client).post<UpdateDiffResponses, UpdateDiffErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}/update/diff',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 按文件集合打包或查询进度
 *
 * 多文件比较增量的接口。第一次没有现成包就入队；之后用同一 JSON 再 POST 这里轮询。pending（202）还没有下载地址；ready 是补丁 zip；full_package 请改下全量包。不要调用管理面的 Job 接口。
 */
export const updatePack = <ThrowOnError extends boolean = false>(options: Options<UpdatePackData, ThrowOnError>) => {
    return (options.client ?? client).post<UpdatePackResponses, UpdatePackErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}/update/pack',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 获取官方文件清单
 *
 * 用来对照本地文件。一次返回全部文件，没有 cursor/limit。草稿不可见；已吊销返回 409 且不含下载地址。ETag 等于该平台线的 root_hash。单文件线 files 只有一项。修复下载默认用 top-level 的 full_package_url。
 */
export const getIntegrity = <ThrowOnError extends boolean = false>(options: Options<GetIntegrityData, ThrowOnError>) => {
    return (options.client ?? client).get<GetIntegrityResponses, GetIntegrityErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}/versions/{version}/integrity',
        ...options
    });
};

/**
 * 上报设备与地理位置
 *
 * 写入设备名册和 custom JSON，并按 IP 查 GeoIP。200 只返回 ip 与地理位置。check 带 device_id 只会更新运行字段，不会覆盖 custom。项目 device_id_policy=none 时返回 400。不会记录明文 device_id。
 */
export const reportClient = <ThrowOnError extends boolean = false>(options: Options<ReportClientData, ThrowOnError>) => {
    return (options.client ?? client).post<ReportClientResponses, ReportClientErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}/clients/report',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 按渠道与平台取更新日志
 *
 * 唯一返回 changelog 正文的原生接口。check 不会带日志。路径指定渠道与平台。from_version 可选：省略时返回最新 default_entries 条；带 from_version 时取 (from, to] 再按新到旧截到 max_entries，HTTP 200。未知渠道 400；渠道 Token 不匹配 404 NOT_FOUND。
 */
export const getChangelog = <ThrowOnError extends boolean = false>(options: Options<GetChangelogData, ThrowOnError>) => {
    return (options.client ?? client).get<GetChangelogResponses, GetChangelogErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/projects/{project_ref}/changelog/{channel}/{os}/{arch}',
        ...options
    });
};
