// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * changelog_versions 数组里的一条版本日志。
 */
export type ChangelogVersion = {
    /**
     * 该版本本地化后的 Markdown 正文。
     */
    changelog: string;
    /**
     * 该版本所在渠道。
     */
    channel: string;
    /**
     * 请求的 os/arch 是否有产物。
     */
    had_artifact_for_request_platform: boolean;
    /**
     * 平台说明。项目关闭 changelog_include_platform_notes 时不出现。
     */
    platform_notes?: string;
    /**
     * 版本状态：published / deprecated / revoked。
     */
    status: 'published' | 'deprecated' | 'revoked';
    /**
     * 该版本更新日志标题。
     */
    title?: string;
    /**
     * 整数版本号；没有则为 null。
     */
    version_integer: number | null;
    /**
     * SemVer 2.0 字符串（不含 +build）；没有则为 null。
     */
    version_semver: string | null;
};

/**
 * 一条客户端公告。locale 是语言，markdown 是展开后的正文。
 */
export type ClientAnnouncement = {
    /**
     * 展示结束时间；null 表示不限制。
     */
    ends_at?: string | null;
    /**
     * 公告 UUID。
     */
    id?: string;
    /**
     * 这条公告的语言。
     */
    locale?: string;
    /**
     * 正文。${site_url} 已按 Referer 展开。
     */
    markdown?: string;
    /**
     * 展示开始时间；null 表示不限制。
     */
    starts_at?: string | null;
    /**
     * 副标题。
     */
    subtitle?: string;
    /**
     * 标题。
     */
    title?: string;
};

/**
 * 公开渠道。不含口令哈希。
 */
export type ClientChannel = {
    /**
     * 渠道显示名。
     */
    name?: string;
    /**
     * 渠道标识，检查更新时作为 channel 查询参数。
     */
    slug?: string;
    /**
     * 稳定性排序，数字越大越稳定。
     */
    stability_rank?: number;
};

/**
 * 公开渠道列表。
 */
export type ClientChannelList = {
    /**
     * 公开渠道列表。
     */
    channels?: Array<ClientChannel>;
};

/**
 * 项目语言。不含 project_id。
 */
export type ClientLanguage = {
    /**
     * 语言代码，例如 zh-CN。
     */
    code?: string;
    /**
     * 给人看的语言名。
     */
    display_name?: string;
    /**
     * 是否项目默认语言。
     */
    is_default?: boolean;
    /**
     * 展示顺序，越小越靠前。
     */
    sort_order?: number;
};

/**
 * 项目语言列表。
 */
export type ClientLanguageList = {
    /**
     * 项目语言列表。
     */
    languages?: Array<ClientLanguage>;
};

/**
 * 设备上报请求体。
 */
export type ClientLoginInput = {
    /**
     * 设备 CPU 架构。
     */
    arch?: string;
    /**
     * 当前渠道。
     */
    channel?: string;
    /**
     * 自定义 JSON，最大 16KiB、深度 8。只在 report 写入。
     */
    custom?: {
        [key: string]: unknown;
    };
    /**
     * 调用方生成的设备标识，1–128 字符。
     */
    device_id: string;
    /**
     * 设备操作系统。
     */
    os?: string;
    /**
     * 当前安装版本。
     */
    version?: string;
};

/**
 * 平台矩阵列表。
 */
export type ClientMatrixList = {
    /**
     * 平台矩阵行。
     */
    matrix?: Array<ClientMatrixRow>;
};

/**
 * 一条 os/arch 包装方式。
 */
export type ClientMatrixRow = {
    /**
     * CPU 架构。
     */
    arch?: string;
    /**
     * 操作系统。
     */
    os?: string;
    /**
     * 该平台是单文件还是多文件。
     */
    package_type?: 'single_file' | 'multi_file';
};

/**
 * 差量查询结果：告诉客户端下全量、下差量，还是下少量单文件。
 */
export type Diff200 = {
    /**
     * 目标版本所在渠道。
     */
    channel: string;
    /**
     * 版本比较方式：semver 或 integer。
     */
    compare_engine: 'integer' | 'semver';
    /**
     * 源清单有、目标清单没有的路径（多文件）。
     */
    deleted_paths?: Array<string>;
    /**
     * diff_mode=binary_delta 时的算法名。
     */
    delta_algo?: string;
    /**
     * full_package / patch_package / binary_delta / file_list。
     */
    diff_mode: 'full_package' | 'patch_package' | 'binary_delta' | 'file_list';
    /**
     * 建议保存的文件名，不参与签名。
     */
    file_name?: string;
    /**
     * 仅 file_list：待下载文件的路径和 URL。
     */
    files?: Array<{
        /**
         * MD5。compact=true 时省略。
         */
        md5?: string;
        /**
         * 相对安装路径，正斜杠。
         */
        path?: string;
        /**
         * 文件 SHA-256。
         */
        sha256?: string;
        /**
         * 字节数。
         */
        size?: number;
        /**
         * 仅当显式要求逐文件 URL 且本页不超过上限时出现。
         */
        url?: string;
    }>;
    /**
     * 无法规范化、已被忽略的路径。
     */
    invalid_paths?: Array<string>;
    /**
     * 要下载的包地址。file_list 模式没有这一项。
     */
    package_url?: string;
    /**
     * 目标线根哈希。
     */
    root_hash: string;
    /**
     * 下载文件的 SHA-256。
     */
    sha256?: string;
    /**
     * 对双号、root_hash、package_url、size、sha256 的签名。
     */
    signature?: string;
    /**
     * 下载字节数。
     */
    size?: number;
    /**
     * 目标整数版本号。
     */
    version_integer: number | null;
    /**
     * 目标 SemVer。
     */
    version_semver: string | null;
};

/**
 * 差量查询请求。
 */
export type DiffRequest = {
    /**
     * 本客户端能应用的差量算法，如 hdiffpatch、bsdiff、xdelta3。
     */
    accepted_delta_algos?: Array<string>;
    /**
     * CPU 架构。
     */
    arch: string;
    /**
     * 能力声明：patch_package / binary_delta / file_list。
     */
    capabilities?: Array<string>;
    /**
     * 可选。填写时必须等于目标版本渠道。
     */
    channel?: string;
    /**
     * 灰度用。不会写入日志。
     */
    device_id?: string;
    /**
     * 硬件变体。
     */
    hw_rev?: string;
    /**
     * 本地单文件哈希。binary_delta 要求它等于官方源包哈希。
     */
    local_sha256?: string;
    /**
     * 操作系统。
     */
    os: string;
    /**
     * 为 true 时不要差量，直接给全量包。
     */
    prefer_full?: boolean;
    /**
     * 当前版本。
     */
    source_version: string;
    /**
     * 目标版本，必须与 check 选出的一致。
     */
    target_version: string;
};

/**
 * 打包请求。needed_paths 是无序集合，顺序和斜杠方向不影响身份。
 */
export type PackRequest = {
    /**
     * CPU 架构。
     */
    arch: string;
    /**
     * 可选。填写时必须等于目标版本渠道。
     */
    channel?: string;
    /**
     * 灰度用。不会写入日志。
     */
    device_id?: string;
    /**
     * 硬件变体。
     */
    hw_rev?: string;
    /**
     * 本地还缺的目标路径，无序集合。本地已有的 KEEP_IF_EXISTS 文件不要放进来。
     */
    needed_paths?: Array<string>;
    /**
     * 操作系统。
     */
    os: string;
    /**
     * 当前版本。
     */
    source_version: string;
    /**
     * check 给出的目标版本。
     */
    target_version: string;
};

/**
 * 打包结果。pending 没有下载地址；ready 是补丁 zip；full_package 指向全量包。
 */
export type Pack200 = {
    /**
     * 目标版本所在渠道。
     */
    channel?: string;
    /**
     * 版本比较方式。
     */
    compare_engine?: 'integer' | 'semver';
    /**
     * 归档格式，原生包是 zip。
     */
    compression?: string;
    /**
     * 应用补丁后应删除的路径。
     */
    deleted_paths?: Array<string>;
    /**
     * ready 时为 patch_package，回落全量时为 full_package。
     */
    diff_mode?: 'full_package' | 'patch_package';
    /**
     * 建议保存的文件名。
     */
    file_name?: string;
    /**
     * 补丁里的文件（path + sha256）。zip 成员名是哈希。
     */
    files?: Array<{
        /**
         * OVERWRITE 覆盖；KEEP_IF_EXISTS 本地已有则保留。
         */
        install_policy?: string;
        /**
         * KEEP 行一般为 false，升级后不要用哈希卡这些文件。
         */
        integrity_check?: boolean;
        /**
         * 相对安装路径，正斜杠。
         */
        path?: string;
        /**
         * 文件 SHA-256。
         */
        sha256?: string;
        /**
         * 字节数。
         */
        size?: number;
    }>;
    /**
     * 无法识别、已忽略的 needed_paths。
     */
    invalid_paths?: Array<string>;
    /**
     * ready 或 full_package 时的下载地址。pending 没有。
     */
    package_url?: string;
    /**
     * 目标线根哈希。
     */
    root_hash?: string;
    /**
     * 下载文件的 SHA-256。
     */
    sha256?: string;
    /**
     * 对关键字段的签名。
     */
    signature?: string;
    /**
     * 下载字节数。
     */
    size?: number;
    /**
     * pending：还在打包；ready：补丁可下；full_package：请改下全量包。
     */
    status: 'pending' | 'ready' | 'full_package';
    /**
     * 目标整数版本号。
     */
    version_integer?: number | null;
    /**
     * 目标 SemVer。
     */
    version_semver?: string | null;
};

/**
 * 统一错误信封：{ error: { code, message, details } }。
 */
export type _Error = {
    /**
     * 错误对象。
     */
    error?: {
        /**
         * 本平面会返回的错误码。code 是英文稳定值。
         */
        code?: 'PROJECT_NOT_FOUND' | 'VERSION_NOT_FOUND' | 'VERSION_LINE_NOT_FOUND' | 'VERSION_NOT_VISIBLE' | 'VERSION_REVOKED' | 'NO_SAFE_TARGET' | 'INTERMEDIATE_UNAVAILABLE' | 'MIN_OS_NOT_MET' | 'CHANNEL_CONFLICT' | 'UNAUTHORIZED' | 'FORBIDDEN' | 'PRECONDITION_FAILED' | 'HW_REV_INCOMPATIBLE' | 'RATE_LIMITED' | 'CHANGELOG_QUERY_INVALID' | 'NOT_FOUND' | 'NOT_READY' | 'INTERNAL_ERROR' | 'INVALID_REQUEST' | 'INVALID_QUERY_PARAM' | 'ENGINE_MISMATCH';
        /**
         * 可选细节。没有时可省略。
         */
        details?: unknown;
        /**
         * 给人看的说明，英文。不要依赖它做逻辑，请看 code。
         */
        message?: string;
    };
};

/**
 * 官方文件清单，用来对照本地安装。一次返回全部文件。
 */
export type Integrity200 = {
    /**
     * 该版本渠道。
     */
    channel: string;
    /**
     * 全量包建议文件名，不参与签名。
     */
    file_name: string;
    /**
     * 完整文件清单。单文件线只有一项。
     */
    files: Array<{
        /**
         * OVERWRITE 覆盖；KEEP_IF_EXISTS 本地已有则保留。
         */
        install_policy: 'OVERWRITE' | 'KEEP_IF_EXISTS';
        /**
         * KEEP 行一般为 false，升级后不要用哈希卡这些文件。
         */
        integrity_check: boolean;
        /**
         * MD5。compact=true 时省略。
         */
        md5?: string;
        /**
         * 相对安装路径，正斜杠。
         */
        path: string;
        /**
         * 文件 SHA-256。
         */
        sha256?: string;
        /**
         * 字节数。
         */
        size: number;
        /**
         * 仅当显式要求逐文件 URL 且总文件数不超过 16 时出现。
         */
        url?: string;
    }>;
    /**
     * 该线全量包的 SHA-256 下载地址。
     */
    full_package_url: string;
    /**
     * single_file 或 multi_file。
     */
    package_type: 'single_file' | 'multi_file';
    /**
     * 清单根哈希；单文件线可为空。
     */
    root_hash: string;
    /**
     * 全量包 SHA-256。
     */
    sha256: string;
    /**
     * 对关键字段的签名。
     */
    signature?: string;
    /**
     * 全量包字节数。
     */
    size: number;
    /**
     * 整数版本号。
     */
    version_integer: number | null;
    /**
     * SemVer。
     */
    version_semver: string | null;
    /**
     * 若发过预切分卷则列出；否则省略。
     */
    volumes?: Array<{
        /**
         * 文件 SHA-256。
         */
        sha256?: string;
        /**
         * 字节数。
         */
        size?: number;
        /**
         * 仅当显式要求逐文件 URL 且本页不超过上限时出现。
         */
        url?: string;
    }> | null;
};

/**
 * 可以给客户端看的项目设置，不含密钥。
 */
export type ProjectPublic = {
    /**
     * 版本比较方式：semver 或 integer。
     */
    compare_engine?: string;
    /**
     * 项目创建时间（UTC）。
     */
    created_at?: string;
    /**
     * 默认语言。
     */
    default_locale?: string;
    /**
     * 设备标识存储策略：hashed / raw / none。
     */
    device_id_policy?: 'hashed' | 'raw' | 'none';
    /**
     * 是否强制 HTTPS。
     */
    force_https?: boolean;
    /**
     * 最低支持版本；低于它会强制更新。
     */
    minimum_supported_version?: string | null;
    /**
     * 检查更新是否必须带项目 Token。
     */
    require_client_token?: boolean;
    /**
     * 项目短名，也可用在 URL 里。
     */
    slug?: string;
    /**
     * public 可直链；private 下载地址带短时签名。
     */
    storage_visibility?: string;
    /**
     * 最近修改时间（UTC）。
     */
    updated_at?: string;
    /**
     * 项目 UUID。
     */
    uuid?: string;
};

/**
 * 探活响应。status 表示进程在；ready 表示数据库和对象存储可用。
 */
export type StatusOutput = {
    /**
     * true：PostgreSQL 能 Ping，且对象存储探测键能 Head。false：尚未就绪。
     */
    ready: boolean;
    /**
     * 进程状态，正常为 ok。
     */
    status: string;
};

/**
 * 检查更新成功体。不含更新日志。多文件不会带逐文件 URL。
 */
export type UpdateCheck200 = {
    /**
     * 开发者随包携带的签名，和 signature 无关。
     */
    artifact_signature?: string;
    /**
     * 版本比较方式：semver 或 integer。
     */
    compare_engine: 'semver' | 'integer';
    /**
     * 仅当 delta_available 为 true。
     */
    delta_algo?: string;
    /**
     * 可以走单文件二进制差量（非降级且客户端声明了能力）。
     */
    delta_available: boolean;
    /**
     * 建议保存的文件名，不参与签名。
     */
    file_name: string;
    /**
     * 是否有可执行更新。
     */
    has_update: boolean;
    /**
     * 目标比当前更旧（吊销/下架回退）。
     */
    is_downgrade: boolean;
    /**
     * 是否强制更新。强制时忽略灰度。
     */
    is_mandatory: boolean;
    /**
     * 目标是 single_file 还是 multi_file。
     */
    package_type: 'single_file' | 'multi_file';
    /**
     * 全量包下载地址，按内容 SHA-256。
     */
    package_url: string;
    /**
     * 目标平台的安装说明。
     */
    platform_notes?: string;
    /**
     * 目标版本发布时间。
     */
    publish_time?: string | null;
    /**
     * 为什么给这个目标：normal / minimum_supported_version / critical_version / revoked / yanked / intermediate。
     */
    reason: 'normal' | 'minimum_supported_version' | 'critical_version' | 'revoked' | 'yanked' | 'intermediate';
    /**
     * 多文件目标线的根哈希；单文件为空。
     */
    root_hash: string;
    /**
     * 全量包 SHA-256。
     */
    sha256: string;
    /**
     * 对整数号、SemVer、root_hash、package_url、size、sha256 的签名。项目没配密钥则省略。
     */
    signature?: string;
    /**
     * 全量包字节数。
     */
    size: number;
    /**
     * 目标渠道，可能和请求的 channel 不同。
     */
    target_channel: string;
    /**
     * 选中的硬件变体；默认变体为 null。
     */
    target_hw_rev: string | null;
    /**
     * 目标整数版本号。
     */
    version_integer: number | null;
    /**
     * 目标 SemVer。
     */
    version_semver: string | null;
};

/**
 * POST /clients/report 返回的地理位置。不含名册行。
 */
export type ClientReportOutput = {
    /**
     * 本次请求的客户端 IP。
     */
    ip: string;
    /**
     * ISO 国家代码；查失败为空串。
     */
    country_code: string;
    /**
     * 一级行政区代码；查失败为空串。
     */
    region_code: string;
    /**
     * 国家/地区多语言地名图。查失败为空对象。
     */
    geo_i18n: {
        [key: string]: unknown;
    };
};

/**
 * POST /update/check 请求体。
 */
export type UpdateCheckRequest = {
    /**
     * 客户端当前版本（整数或 SemVer）。
     */
    current_version: string;
    /**
     * 操作系统，如 windows、linux、macos、android。别名会规范化。
     */
    os: string;
    /**
     * CPU 架构，如 x86_64、arm64。
     */
    arch: string;
    /**
     * 渠道 slug，默认 stable。
     */
    channel?: string;
    /**
     * 硬件变体。
     */
    hw_rev?: string;
    /**
     * 系统版本，用于最低系统要求判断。
     */
    os_version?: string;
    /**
     * 设备标识，用于灰度和遥测。
     */
    device_id?: string;
    /**
     * 能力字符串数组。已知：full_package、file_list、patch_package、binary_delta。
     */
    capabilities?: Array<string>;
    /**
     * 非空即自动授予 binary_delta 能力。
     */
    accepted_delta_algos?: Array<string>;
};

/**
 * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
 */
export type ProjectRef = string;

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type GetHealthResponses = {
    /**
     * 进程存活。ready 表示数据库和对象存储是否可用。
     */
    200: StatusOutput;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetOpenApiSpecData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/openapi.json';
};

export type GetOpenApiSpecResponses = {
    /**
     * OpenAPI JSON 文档。
     */
    200: unknown;
};

export type GetPublicProjectData = {
    body?: never;
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_ref}';
};

export type GetPublicProjectErrors = {
    /**
     * 项目要求客户端 Token 时未提供或无效（UNAUTHORIZED）。
     */
    401: _Error;
    /**
     * 项目强制 HTTPS 但当前不是 HTTPS（FORBIDDEN）。
     */
    403: _Error;
    /**
     * 项目不存在（PROJECT_NOT_FOUND）。
     */
    404: _Error;
};

export type GetPublicProjectError = GetPublicProjectErrors[keyof GetPublicProjectErrors];

export type GetPublicProjectResponses = {
    /**
     * 成功。
     */
    200: ProjectPublic;
};

export type GetPublicProjectResponse = GetPublicProjectResponses[keyof GetPublicProjectResponses];

export type OptionsPublicProjectData = {
    body?: never;
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_ref}';
};

export type OptionsPublicProjectErrors = {
    /**
     * 项目不存在（PROJECT_NOT_FOUND）。
     */
    404: _Error;
};

export type OptionsPublicProjectError = OptionsPublicProjectErrors[keyof OptionsPublicProjectErrors];

export type OptionsPublicProjectResponses = {
    /**
     * 无正文。
     */
    204: void;
};

export type OptionsPublicProjectResponse = OptionsPublicProjectResponses[keyof OptionsPublicProjectResponses];

export type ListClientAnnouncementsData = {
    body?: never;
    headers?: {
        'Accept-Language'?: string;
        'If-None-Match'?: string;
    };
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
    };
    query?: {
        /**
         * 已安装版本。省略则不匹配按版本限定的公告。
         */
        version?: string;
        /**
         * 操作系统，如 windows、linux、macos、android。别名会规范化。
         */
        os?: string;
        /**
         * CPU 架构，如 x86_64、arm64。
         */
        arch?: string;
        /**
         * 语言。省略时按 Accept-Language 和项目默认回落。
         */
        locale?: string;
    };
    url: '/api/v1/projects/{project_ref}/announcements';
};

export type ListClientAnnouncementsErrors = {
    /**
     * 查询参数不合法（INVALID_QUERY_PARAM）。
     */
    400: _Error;
    /**
     * 项目要求客户端 Token 时未提供或无效（UNAUTHORIZED）。
     */
    401: _Error;
    /**
     * 项目不存在（PROJECT_NOT_FOUND）。
     */
    404: _Error;
};

export type ListClientAnnouncementsError = ListClientAnnouncementsErrors[keyof ListClientAnnouncementsErrors];

export type ListClientAnnouncementsResponses = {
    /**
     * 按管理端排序返回当前可见公告。空列表也是成功。
     */
    200: {
        announcements?: Array<ClientAnnouncement>;
    };
};

export type ListClientAnnouncementsResponse = ListClientAnnouncementsResponses[keyof ListClientAnnouncementsResponses];

export type ListClientChannelsData = {
    body?: never;
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_ref}/channels';
};

export type ListClientChannelsErrors = {
    /**
     * 未授权（UNAUTHORIZED）。
     */
    401: _Error;
    /**
     * 项目不存在（PROJECT_NOT_FOUND）。
     */
    404: _Error;
};

export type ListClientChannelsError = ListClientChannelsErrors[keyof ListClientChannelsErrors];

export type ListClientChannelsResponses = {
    /**
     * 成功。
     */
    200: ClientChannelList;
};

export type ListClientChannelsResponse = ListClientChannelsResponses[keyof ListClientChannelsResponses];

export type GetStoreFeedListingData = {
    body?: never;
    headers?: {
        /**
         * 浏览器语言，省略 locale 时用来回落。
         */
        'Accept-Language'?: string;
        /**
         * 上次的 ETag。未变化时返回 304。
         */
        'If-None-Match'?: string;
    };
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
        /**
         * 商店协议名，如 sparkle、winget。
         */
        protocol: string;
        /**
         * 商店 listing 的 slug。
         */
        listing_slug: string;
    };
    query: {
        /**
         * 渠道 slug，默认 stable。
         */
        channel?: string;
        /**
         * 操作系统，如 windows、linux、macos、android。别名会规范化。
         */
        os: string;
        /**
         * CPU 架构，如 x86_64、arm64。
         */
        arch: string;
        /**
         * 硬件变体。
         */
        hw_rev?: string;
        /**
         * 客户端当前版本（整数或 SemVer）。
         */
        current_version?: string;
        /**
         * 更新日志语言，优先于 locale。
         */
        changelog_locale?: string;
        /**
         * 语言。省略时按 Accept-Language 和项目默认回落。
         */
        locale?: string;
    };
    url: '/api/v1/projects/{project_ref}/store/{protocol}/{listing_slug}';
};

export type GetStoreFeedListingErrors = {
    /**
     * 渠道未知或缺少 os/arch（INVALID_QUERY_PARAM）。
     */
    400: _Error;
    /**
     * 开启了客户端 Token 或商店 Token，但凭证无效（UNAUTHORIZED）。
     */
    401: _Error;
    /**
     * 纯文本 404：未知协议或该项目未启用此商店 listing。正文不会是通用 zip。项目不存在时返回 JSON PROJECT_NOT_FOUND。
     */
    404: unknown;
};

export type GetStoreFeedListingError = GetStoreFeedListingErrors[keyof GetStoreFeedListingErrors];

export type GetStoreFeedListingResponses = {
    /**
     * 所请求协议的商店文档。Sparkle appcast 是带 sparkle 命名空间的 RSS 2.0：每条含 title、pubDate、sparkle:version，以及一个 enclosure（稳定文件名 URL、大小、类型）和 sparkle:edSignature。
     */
    200: string;
    /**
     * Tauri 动态端点：客户端已是最新匿名可见版本，或当前版本服务器不认识。无正文、无 ETag。Sparkle 这类列表文档不会返回 204。
     */
    204: void;
};

export type GetStoreFeedListingResponse = GetStoreFeedListingResponses[keyof GetStoreFeedListingResponses];

export type PostStoreFeedListingData = {
    /**
     * 该协议自己的查询体，例如 WinGet 搜索。
     */
    body?: {
        [key: string]: unknown;
    };
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
        /**
         * 商店协议名，如 sparkle、winget。
         */
        protocol: string;
        /**
         * 商店 listing 的 slug。
         */
        listing_slug: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_ref}/store/{protocol}/{listing_slug}';
};

export type PostStoreFeedListingErrors = {
    /**
     * 开启了客户端 Token 或商店 Token，但凭证无效（UNAUTHORIZED）。
     */
    401: _Error;
    /**
     * 纯文本 404：未知协议或该项目未启用此商店 listing。
     */
    404: unknown;
};

export type PostStoreFeedListingError = PostStoreFeedListingErrors[keyof PostStoreFeedListingErrors];

export type PostStoreFeedListingResponses = {
    /**
     * WinGet manifestSearch 的 JSON，Data 数组包在里面。
     */
    200: string;
};

export type PostStoreFeedListingResponse = PostStoreFeedListingResponses[keyof PostStoreFeedListingResponses];

export type GetStoreFeedData = {
    body?: never;
    headers?: {
        /**
         * 浏览器语言，省略 locale 时用来回落。
         */
        'Accept-Language'?: string;
        /**
         * 上次的 ETag。未变化时返回 304。
         */
        'If-None-Match'?: string;
    };
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
        /**
         * 商店协议名，如 sparkle、winget。
         */
        protocol: string;
        /**
         * 商店 listing 的 slug。
         */
        listing_slug: string;
        /**
         * 协议文档名，如 appcast.xml。
         */
        doc: string;
    };
    query: {
        /**
         * 渠道 slug，默认 stable。
         */
        channel?: string;
        /**
         * 操作系统，如 windows、linux、macos、android。别名会规范化。
         */
        os: string;
        /**
         * CPU 架构，如 x86_64、arm64。
         */
        arch: string;
        /**
         * 硬件变体。
         */
        hw_rev?: string;
        /**
         * 客户端当前版本（整数或 SemVer）。
         */
        current_version?: string;
        /**
         * 更新日志语言，优先于 locale。
         */
        changelog_locale?: string;
        /**
         * 语言。省略时按 Accept-Language 和项目默认回落。
         */
        locale?: string;
    };
    url: '/api/v1/projects/{project_ref}/store/{protocol}/{listing_slug}/{doc}';
};

export type GetStoreFeedErrors = {
    /**
     * 渠道未知或缺少 os/arch（INVALID_QUERY_PARAM）。
     */
    400: _Error;
    /**
     * 开启了客户端 Token 或商店 Token，但凭证无效（UNAUTHORIZED）。
     */
    401: _Error;
    /**
     * 纯文本 404：未知协议或该项目未启用此商店 listing。正文不会是通用 zip。项目不存在时返回 JSON PROJECT_NOT_FOUND。
     */
    404: unknown;
};

export type GetStoreFeedError = GetStoreFeedErrors[keyof GetStoreFeedErrors];

export type GetStoreFeedResponses = {
    /**
     * 所请求协议的商店文档。Sparkle appcast 是带 sparkle 命名空间的 RSS 2.0：每条含 title、pubDate、sparkle:version，以及一个 enclosure（稳定文件名 URL、大小、类型）和 sparkle:edSignature。
     */
    200: string;
    /**
     * Tauri 动态端点：客户端已是最新匿名可见版本，或当前版本服务器不认识。无正文、无 ETag。Sparkle 这类列表文档不会返回 204。
     */
    204: void;
};

export type GetStoreFeedResponse = GetStoreFeedResponses[keyof GetStoreFeedResponses];

export type PostStoreFeedData = {
    /**
     * 该协议自己的查询体，例如 WinGet 搜索。
     */
    body?: {
        [key: string]: unknown;
    };
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
        /**
         * 商店协议名，如 sparkle、winget。
         */
        protocol: string;
        /**
         * 商店 listing 的 slug。
         */
        listing_slug: string;
        /**
         * 协议文档名，如 appcast.xml。
         */
        doc: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_ref}/store/{protocol}/{listing_slug}/{doc}';
};

export type PostStoreFeedErrors = {
    /**
     * 开启了客户端 Token 或商店 Token，但凭证无效（UNAUTHORIZED）。
     */
    401: _Error;
    /**
     * 纯文本 404：未知协议或该项目未启用此商店 listing。
     */
    404: unknown;
};

export type PostStoreFeedError = PostStoreFeedErrors[keyof PostStoreFeedErrors];

export type PostStoreFeedResponses = {
    /**
     * WinGet manifestSearch 的 JSON，Data 数组包在里面。
     */
    200: string;
};

export type PostStoreFeedResponse = PostStoreFeedResponses[keyof PostStoreFeedResponses];

export type ListClientLanguagesData = {
    body?: never;
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_ref}/languages';
};

export type ListClientLanguagesErrors = {
    /**
     * 项目要求客户端 Token 时未提供或无效（UNAUTHORIZED）。
     */
    401: _Error;
    /**
     * 项目不存在（PROJECT_NOT_FOUND）。
     */
    404: _Error;
};

export type ListClientLanguagesError = ListClientLanguagesErrors[keyof ListClientLanguagesErrors];

export type ListClientLanguagesResponses = {
    /**
     * 成功。
     */
    200: ClientLanguageList;
};

export type ListClientLanguagesResponse = ListClientLanguagesResponses[keyof ListClientLanguagesResponses];

export type ListClientMatrixData = {
    body?: never;
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_ref}/matrix';
};

export type ListClientMatrixErrors = {
    /**
     * 未授权（UNAUTHORIZED）。
     */
    401: _Error;
    /**
     * 项目不存在（PROJECT_NOT_FOUND）。
     */
    404: _Error;
};

export type ListClientMatrixError = ListClientMatrixErrors[keyof ListClientMatrixErrors];

export type ListClientMatrixResponses = {
    /**
     * 成功。
     */
    200: ClientMatrixList;
};

export type ListClientMatrixResponse = ListClientMatrixResponses[keyof ListClientMatrixResponses];

export type GetProjectMediaData = {
    body?: never;
    headers?: {
        /**
         * HTTP Range，按字节区间下载。
         */
        Range?: string;
    };
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
        /**
         * 媒体 UUID。
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_ref}/media/{id}';
};

export type GetProjectMediaErrors = {
    /**
     * 对象或项目不存在。
     */
    404: _Error;
};

export type GetProjectMediaError = GetProjectMediaErrors[keyof GetProjectMediaErrors];

export type GetProjectMediaResponses = {
    /**
     * 原始字节和元数据里的 Content-Type。
     */
    200: Blob | File;
    /**
     * 部分字节区间。
     */
    206: Blob | File;
};

export type GetProjectMediaResponse = GetProjectMediaResponses[keyof GetProjectMediaResponses];

export type HeadProjectMediaData = {
    body?: never;
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
        /**
         * 媒体 UUID。
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_ref}/media/{id}';
};

export type HeadProjectMediaErrors = {
    /**
     * 对象或项目不存在。
     */
    404: _Error;
};

export type HeadProjectMediaError = HeadProjectMediaErrors[keyof HeadProjectMediaErrors];

export type HeadProjectMediaResponses = {
    /**
     * 只返回响应头。
     */
    200: unknown;
};

export type DownloadPackageData = {
    body?: never;
    headers?: {
        /**
         * HTTP Range，按字节区间下载，例如 bytes=0-1048575。
         */
        Range?: string;
    };
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
        /**
         * 内容 SHA-256（可带扩展名）。不是文件名。
         */
        ref: string;
    };
    query?: {
        /**
         * 硬件变体。
         */
        hw_rev?: string;
    };
    url: '/api/v1/projects/{project_ref}/packages/{ref}';
};

export type DownloadPackageErrors = {
    /**
     * 没有这个 SHA-256，或格式不对（NOT_FOUND）。
     */
    404: _Error;
};

export type DownloadPackageError = DownloadPackageErrors[keyof DownloadPackageErrors];

export type DownloadPackageResponses = {
    /**
     * 安装包字节。
     */
    200: Blob | File;
    /**
     * 部分字节区间。
     */
    206: Blob | File;
};

export type DownloadPackageResponse = DownloadPackageResponses[keyof DownloadPackageResponses];

export type HeadPackageData = {
    body?: never;
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
        /**
         * 内容 SHA-256（可带扩展名）。不是文件名。
         */
        ref: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_ref}/packages/{ref}';
};

export type HeadPackageErrors = {
    /**
     * 私有存储项目缺少、过期或无效的 exp/sig 下载签名（FORBIDDEN）。
     */
    403: _Error;
};

export type HeadPackageError = HeadPackageErrors[keyof HeadPackageErrors];

export type HeadPackageResponses = {
    /**
     * 只探测响应头。私有存储项目仍需要 exp/sig。
     */
    200: unknown;
};

export type ReportTelemetryData = {
    /**
     * 更新进度上报。
     */
    body: {
        arch: string;
        channel: string;
        /**
         * 原始设备号，可选。按项目 device_id_policy 存储，不会写入日志。
         */
        device_id?: string;
        diff_mode?: 'full_package' | 'patch_package' | 'binary_delta' | 'file_list';
        error_code?: string;
        error_message?: string;
        from_version: string;
        os: string;
        status: 'downloading' | 'applying' | 'installed' | 'failed' | 'rolled_back';
        to_version: string;
    };
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_ref}/telemetry/report';
};

export type ReportTelemetryErrors = {
    /**
     * 校验失败：缺字段或未知 status。
     */
    400: _Error;
    /**
     * Project not found.
     */
    404: _Error;
    /**
     * 过于频繁（RATE_LIMITED），带 Retry-After。
     */
    429: _Error;
};

export type ReportTelemetryError = ReportTelemetryErrors[keyof ReportTelemetryErrors];

export type ReportTelemetryResponses = {
    /**
     * 事件已接受。遥测失败不应卡住更新。
     */
    202: {
        status?: string;
    };
};

export type ReportTelemetryResponse = ReportTelemetryResponses[keyof ReportTelemetryResponses];

export type CheckUpdateData = {
    body: UpdateCheckRequest;
    headers?: {
        /**
         * 与当前目录 ETag 比对。命中一律 304，不管本来会是 200 还是 204。
         */
        'If-None-Match'?: string;
        /**
         * 隐藏渠道的密钥，按 SHA-256 比对。缺了或错了只会跳过这些渠道，检查更新不会因此 403。
         */
        'X-Channel-Token'?: string;
    };
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_ref}/update/check';
};

export type CheckUpdateErrors = {
    /**
     * JSON 缺少 current_version、os 或 arch（INVALID_QUERY_PARAM）；current_version 无法解析（ENGINE_MISMATCH）。GET 本路径 404。
     */
    400: _Error;
    /**
     * VERSION_NOT_FOUND.
     */
    404: _Error;
    /**
     * 没有安全目标、中间包不可用或系统版本不够。错误恒为 private, no-store，避免 CDN 把错误当成 204。
     */
    409: _Error;
};

export type CheckUpdateError = CheckUpdateErrors[keyof CheckUpdateErrors];

export type CheckUpdateResponses = {
    /**
     * 可执行更新（普通、强制、中继或降级）。
     */
    200: UpdateCheck200;
    /**
     * 没有更新：当前已是最新可见版本，且未被吊销或下架。
     */
    204: void;
};

export type CheckUpdateResponse = CheckUpdateResponses[keyof CheckUpdateResponses];

export type UpdateDiffData = {
    /**
     * 本地文件身份和能力协商。
     */
    body: DiffRequest;
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_ref}/update/diff';
};

export type UpdateDiffErrors = {
    /**
     * 字段缺失或不合法（INVALID_QUERY_PARAM），或渠道冲突（CHANNEL_CONFLICT）。
     */
    400: _Error;
    /**
     * 源或目标版本不存在、草稿/未 stamp 不可见，或没有就绪的平台线。
     */
    404: _Error;
    /**
     * 目标版本已吊销（VERSION_REVOKED）。恒为 private, no-store。
     */
    409: _Error;
    /**
     * 指定目标并非强制，且灰度未命中（PRECONDITION_FAILED）。
     */
    412: _Error;
};

export type UpdateDiffError = UpdateDiffErrors[keyof UpdateDiffErrors];

export type UpdateDiffResponses = {
    /**
     * 这一对源/目标版本的差量方案（含 file_list 例外）。
     */
    200: Diff200;
};

export type UpdateDiffResponse = UpdateDiffResponses[keyof UpdateDiffResponses];

export type UpdatePackData = {
    /**
     * 需要打包的路径和版本身份。
     */
    body: PackRequest;
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_ref}/update/pack';
};

export type UpdatePackErrors = {
    /**
     * 查询不合法或渠道冲突。
     */
    400: _Error;
    /**
     * 版本不存在、草稿/未 stamp 不可见，或没有平台线。
     */
    404: _Error;
    /**
     * VERSION_REVOKED.
     */
    409: _Error;
    /**
     * 指定的非强制目标灰度未命中（PRECONDITION_FAILED）。
     */
    412: _Error;
};

export type UpdatePackError = UpdatePackErrors[keyof UpdatePackErrors];

export type UpdatePackResponses = {
    /**
     * 缓存命中为 ready；未知路径、体积门限或失败任务为 full_package。
     */
    200: Pack200;
    /**
     * 正在打包。用同一请求体再次 POST 本接口。还没有 package_url。
     */
    202: Pack200;
};

export type UpdatePackResponse = UpdatePackResponses[keyof UpdatePackResponses];

export type GetIntegrityData = {
    body?: never;
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
        /**
         * 已安装版本。省略则不匹配按版本限定的公告。
         */
        version: string;
    };
    query: {
        /**
         * 操作系统，如 windows、linux、macos、android。别名会规范化。
         */
        os: string;
        /**
         * CPU 架构，如 x86_64、arm64。
         */
        arch: string;
        /**
         * 清单里返回哪些哈希。非法值 400。
         */
        hash_algo?: 'sha256' | 'md5' | 'both';
        /**
         * 为 true 时不返回 md5。
         */
        compact?: boolean;
        /**
         * 为 true 且总文件数不超过 16 时，给每条文件一个下载 URL。
         */
        include_file_urls?: boolean;
        /**
         * 硬件变体。
         */
        hw_rev?: string;
        /**
         * 渠道 slug，默认 stable。
         */
        channel?: string;
    };
    url: '/api/v1/projects/{project_ref}/versions/{version}/integrity';
};

export type GetIntegrityErrors = {
    /**
     * 缺少 os/arch 或 hash_algo 不合法（INVALID_QUERY_PARAM），或渠道冲突（CHANNEL_CONFLICT）。
     */
    400: _Error;
    /**
     * 版本不存在、草稿不可见，或没有平台线。
     */
    404: _Error;
    /**
     * 版本已吊销（VERSION_REVOKED）。错误体不含任何下载地址。恒为 private, no-store。
     */
    409: _Error;
};

export type GetIntegrityError = GetIntegrityErrors[keyof GetIntegrityErrors];

export type GetIntegrityResponses = {
    /**
     * 完整文件清单，以及全量包身份和签名。没有 cursor/limit。
     */
    200: Integrity200;
};

export type GetIntegrityResponse = GetIntegrityResponses[keyof GetIntegrityResponses];

export type ReportClientData = {
    body: ClientLoginInput;
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_ref}/clients/report';
};

export type ReportClientErrors = {
    /**
     * 请求体不合法（INVALID_REQUEST）。
     */
    400: _Error;
    /**
     * 项目要求客户端 Token 时未提供或无效（UNAUTHORIZED）。
     */
    401: _Error;
    /**
     * 项目不存在（PROJECT_NOT_FOUND）。
     */
    404: _Error;
};

export type ReportClientError = ReportClientErrors[keyof ReportClientErrors];

export type ReportClientResponses = {
    /**
     * 地理位置（无 client 包装）。
     */
    200: ClientReportOutput;
};

export type ReportClientResponse = ReportClientResponses[keyof ReportClientResponses];

export type GetChangelogData = {
    body?: never;
    headers?: {
        /**
         * 上次的 ETag。未变化时返回 304。
         */
        'If-None-Match'?: string;
        /**
         * Token 保护渠道的密钥。不匹配返回 404 NOT_FOUND。
         */
        'X-Channel-Token'?: string;
    };
    path: {
        /**
         * 项目 UUID、当前 slug，或未过期的 slug 别名。过期别名返回 404 PROJECT_NOT_FOUND。
         */
        project_ref: string;
        /**
         * 渠道 slug。未知渠道 400 INVALID_QUERY_PARAM。
         */
        channel: string;
        /**
         * 操作系统，如 windows、linux、macos、android。别名会规范化。
         */
        os: string;
        /**
         * CPU 架构，如 x86_64、arm64。
         */
        arch: string;
    };
    query?: {
        /**
         * 日志范围起点（不含该版本）。省略则返回最新若干条。
         */
        from_version?: string;
        /**
         * 日志范围终点。省略时为该渠道最高可见版本。
         */
        to_version?: string;
        /**
         * 日志范围：range_all（全部）、range_platform（该平台有包的版本）、target_only（只看目标版本）。
         */
        changelog_scope?: 'range_all' | 'range_platform' | 'target_only';
        /**
         * 排版：aggregated 汇总、structured 按版本、both 两者都要。
         */
        changelog_layout?: 'aggregated' | 'structured' | 'both';
        /**
         * 是否包含已吊销版本的历史日志。
         */
        changelog_include_revoked?: boolean;
        /**
         * 是否附上该平台线的说明。
         */
        changelog_include_platform_notes?: boolean;
        /**
         * 更新日志语言，优先于 locale。
         */
        changelog_locale?: string;
        /**
         * 语言。省略时用项目默认。不读 Accept-Language。
         */
        locale?: string;
    };
    url: '/api/v1/projects/{project_ref}/changelog/{channel}/{os}/{arch}';
};

export type GetChangelogErrors = {
    /**
     * 日志查询参数不合法（CHANGELOG_QUERY_INVALID）。
     */
    400: _Error;
    /**
     * 项目不存在（PROJECT_NOT_FOUND）、版本未知（VERSION_NOT_FOUND）或渠道 Token 不匹配（NOT_FOUND）。
     */
    404: _Error;
};

export type GetChangelogError = GetChangelogErrors[keyof GetChangelogErrors];

export type GetChangelogResponses = {
    /**
     * 按范围和排版返回的更新日志。
     */
    200: {
        /**
         * 汇总后的 Markdown。layout 为 aggregated 或 both 时出现。
         */
        changelog?: string;
        changelog_versions?: Array<ChangelogVersion>;
    };
};

export type GetChangelogResponse = GetChangelogResponses[keyof GetChangelogResponses];
