/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admins': RouteRecordInfo<
      '/admins',
      '/admins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/geoip': RouteRecordInfo<
      '/geoip',
      '/geoip',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nodes': RouteRecordInfo<
      '/nodes',
      '/nodes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/[projectRef]': RouteRecordInfo<
      '/projects/[projectRef]',
      '/projects/:projectRef',
      { projectRef: ParamValue<true> },
      { projectRef: ParamValue<false> },
      | '/projects/[projectRef]/announcements'
      | '/projects/[projectRef]/audit'
      | '/projects/[projectRef]/channels'
      | '/projects/[projectRef]/clients'
      | '/projects/[projectRef]/hw-revs'
      | '/projects/[projectRef]/languages'
      | '/projects/[projectRef]/matrix'
      | '/projects/[projectRef]/overview'
      | '/projects/[projectRef]/release'
      | '/projects/[projectRef]/settings'
      | '/projects/[projectRef]/tokens'
      | '/projects/[projectRef]/versions/'
      | '/projects/[projectRef]/versions/[version]'
      | '/projects/[projectRef]/versions/[version]/'
      | '/projects/[projectRef]/versions/[version]/gray'
    >,
    '/projects/[projectRef]/announcements': RouteRecordInfo<
      '/projects/[projectRef]/announcements',
      '/projects/:projectRef/announcements',
      { projectRef: ParamValue<true> },
      { projectRef: ParamValue<false> },
      | never
    >,
    '/projects/[projectRef]/audit': RouteRecordInfo<
      '/projects/[projectRef]/audit',
      '/projects/:projectRef/audit',
      { projectRef: ParamValue<true> },
      { projectRef: ParamValue<false> },
      | never
    >,
    '/projects/[projectRef]/channels': RouteRecordInfo<
      '/projects/[projectRef]/channels',
      '/projects/:projectRef/channels',
      { projectRef: ParamValue<true> },
      { projectRef: ParamValue<false> },
      | never
    >,
    '/projects/[projectRef]/clients': RouteRecordInfo<
      '/projects/[projectRef]/clients',
      '/projects/:projectRef/clients',
      { projectRef: ParamValue<true> },
      { projectRef: ParamValue<false> },
      | never
    >,
    '/projects/[projectRef]/hw-revs': RouteRecordInfo<
      '/projects/[projectRef]/hw-revs',
      '/projects/:projectRef/hw-revs',
      { projectRef: ParamValue<true> },
      { projectRef: ParamValue<false> },
      | never
    >,
    '/projects/[projectRef]/languages': RouteRecordInfo<
      '/projects/[projectRef]/languages',
      '/projects/:projectRef/languages',
      { projectRef: ParamValue<true> },
      { projectRef: ParamValue<false> },
      | never
    >,
    '/projects/[projectRef]/matrix': RouteRecordInfo<
      '/projects/[projectRef]/matrix',
      '/projects/:projectRef/matrix',
      { projectRef: ParamValue<true> },
      { projectRef: ParamValue<false> },
      | never
    >,
    '/projects/[projectRef]/overview': RouteRecordInfo<
      '/projects/[projectRef]/overview',
      '/projects/:projectRef/overview',
      { projectRef: ParamValue<true> },
      { projectRef: ParamValue<false> },
      | never
    >,
    '/projects/[projectRef]/release': RouteRecordInfo<
      '/projects/[projectRef]/release',
      '/projects/:projectRef/release',
      { projectRef: ParamValue<true> },
      { projectRef: ParamValue<false> },
      | never
    >,
    '/projects/[projectRef]/settings': RouteRecordInfo<
      '/projects/[projectRef]/settings',
      '/projects/:projectRef/settings',
      { projectRef: ParamValue<true> },
      { projectRef: ParamValue<false> },
      | never
    >,
    '/projects/[projectRef]/tokens': RouteRecordInfo<
      '/projects/[projectRef]/tokens',
      '/projects/:projectRef/tokens',
      { projectRef: ParamValue<true> },
      { projectRef: ParamValue<false> },
      | never
    >,
    '/projects/[projectRef]/versions/': RouteRecordInfo<
      '/projects/[projectRef]/versions/',
      '/projects/:projectRef/versions',
      { projectRef: ParamValue<true> },
      { projectRef: ParamValue<false> },
      | never
    >,
    '/projects/[projectRef]/versions/[version]': RouteRecordInfo<
      '/projects/[projectRef]/versions/[version]',
      '/projects/:projectRef/versions/:version',
      { projectRef: ParamValue<true>, version: ParamValue<true> },
      { projectRef: ParamValue<false>, version: ParamValue<false> },
      | '/projects/[projectRef]/versions/[version]/'
      | '/projects/[projectRef]/versions/[version]/gray'
    >,
    '/projects/[projectRef]/versions/[version]/': RouteRecordInfo<
      '/projects/[projectRef]/versions/[version]/',
      '/projects/:projectRef/versions/:version',
      { projectRef: ParamValue<true>, version: ParamValue<true> },
      { projectRef: ParamValue<false>, version: ParamValue<false> },
      | never
    >,
    '/projects/[projectRef]/versions/[version]/gray': RouteRecordInfo<
      '/projects/[projectRef]/versions/[version]/gray',
      '/projects/:projectRef/versions/:version/gray',
      { projectRef: ParamValue<true>, version: ParamValue<true> },
      { projectRef: ParamValue<false>, version: ParamValue<false> },
      | never
    >,
    '/security': RouteRecordInfo<
      '/security',
      '/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admins.vue': {
      routes:
        | '/admins'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/geoip.vue': {
      routes:
        | '/geoip'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/nodes.vue': {
      routes:
        | '/nodes'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/index.vue': {
      routes:
        | '/projects/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[projectRef].vue': {
      routes:
        | '/projects/[projectRef]'
        | '/projects/[projectRef]/announcements'
        | '/projects/[projectRef]/audit'
        | '/projects/[projectRef]/channels'
        | '/projects/[projectRef]/clients'
        | '/projects/[projectRef]/hw-revs'
        | '/projects/[projectRef]/languages'
        | '/projects/[projectRef]/matrix'
        | '/projects/[projectRef]/overview'
        | '/projects/[projectRef]/release'
        | '/projects/[projectRef]/settings'
        | '/projects/[projectRef]/tokens'
        | '/projects/[projectRef]/versions/'
        | '/projects/[projectRef]/versions/[version]'
        | '/projects/[projectRef]/versions/[version]/'
        | '/projects/[projectRef]/versions/[version]/gray'
      views:
        | 'default'
      pathParamNames:
        | 'projectRef'
    }
    'src/pages/projects/[projectRef]/announcements.vue': {
      routes:
        | '/projects/[projectRef]/announcements'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[projectRef]/audit.vue': {
      routes:
        | '/projects/[projectRef]/audit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[projectRef]/channels.vue': {
      routes:
        | '/projects/[projectRef]/channels'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[projectRef]/clients.vue': {
      routes:
        | '/projects/[projectRef]/clients'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[projectRef]/hw-revs.vue': {
      routes:
        | '/projects/[projectRef]/hw-revs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[projectRef]/languages.vue': {
      routes:
        | '/projects/[projectRef]/languages'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[projectRef]/matrix.vue': {
      routes:
        | '/projects/[projectRef]/matrix'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[projectRef]/overview.vue': {
      routes:
        | '/projects/[projectRef]/overview'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[projectRef]/release.vue': {
      routes:
        | '/projects/[projectRef]/release'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[projectRef]/settings.vue': {
      routes:
        | '/projects/[projectRef]/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[projectRef]/tokens.vue': {
      routes:
        | '/projects/[projectRef]/tokens'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[projectRef]/versions/index.vue': {
      routes:
        | '/projects/[projectRef]/versions/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[projectRef]/versions/[version].vue': {
      routes:
        | '/projects/[projectRef]/versions/[version]'
        | '/projects/[projectRef]/versions/[version]/'
        | '/projects/[projectRef]/versions/[version]/gray'
      views:
        | 'default'
      pathParamNames:
        | 'version'
    }
    'src/pages/projects/[projectRef]/versions/[version]/index.vue': {
      routes:
        | '/projects/[projectRef]/versions/[version]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[projectRef]/versions/[version]/gray.vue': {
      routes:
        | '/projects/[projectRef]/versions/[version]/gray'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/security.vue': {
      routes:
        | '/security'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
