# KiriCTF 本地 Redis 配置。修改后需重启容器才会生效。
bind 0.0.0.0
protected-mode yes
port 6379
daemonize no
logfile ""
dir /data
requirepass aa4BTLHj85zZsebO3ugcja1Mn20HIB5r
appendonly yes
appendfilename "appendonly.aof"
aof-use-rdb-preamble yes
save 60 1000
tcp-keepalive 300
timeout 0
